name: nail_designer_app
description: "App de agendamento para Nail Designer"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase base
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.4
  firebase_app_check: ^0.2.2+3

  # State Management
  flutter_riverpod: ^2.4.0

  # Navegação moderna
  go_router: ^12.1.1

  # Fonts e estilo
  google_fonts: ^6.1.0

  # Ícones iOS
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0

# ⚠️ flutter_local_notifications removido temporariamente
# Caso deseje reativar, use uma versão segura + config especial

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo_oficial_semfundo.png
